// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzggltxfxcwfrcaxwiqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Z2dsdHhmeGN3ZnJjYXh3aXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjI1MDAsImV4cCI6MjA2NjA5ODUwMH0.zoCCIXu83ciWyCiL3LgJD3Vay73N6eOjrHaMsLkDeB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);